name: journeyhazard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+9

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_barcode_scanner: any
  localize_and_translate: ^4.0.1
  image_picker: ^0.7.4
  sqflite: ^1.3.0
  color: ^2.1.1
  http: ^0.13.1
  dio: ^4.0.0
  after_layout: ^1.0.7+2
  json_annotation: ^4.0.0
  flutter_svg: ^0.21.0+1
  dartz: ^0.9.1
  url_launcher: ^6.0.3
  file_picker: ^3.0.1
  package_info: ^2.0.2
  flutter_screenutil: ^1.1.0
  cached_network_image: ^2.2.0+1
  flutter_launcher_icons: ^0.9.0
  path_provider: ^2.0.1
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  flutter_staggered_grid_view: ^0.3.0
  flushbar: ^1.10.4
  flutter_spinkit: ^4.1.2
  simple_animations: ^1.3.3
  date_utils: ^0.2.0
  flutter_typeahead: ^1.8.7
  intl: ^0.17.0
  scoped_model: ^1.0.1
  flutter_webview_plugin: any
  google_maps_flutter: ^2.0.6
  geolocator:
  geocoder: any
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.2.2
  in_app_update: ^2.0.0
  native_updater: ^0.1.0
  new_version: ^0.2.0
  flutter_animarker: ^3.2.0
  permission_handler:
  intl_phone_number_input: ^0.7.0+2
  wakelock: ^0.5.1
  flutter_polyline_points: ^1.0.0
  sliding_sheet: ^0.5.2
  carousel_slider: ^4.0.0
  dropdown_search: ^2.0.1
  lottie: ^1.2.0

#  flutter_speed_dial: ^4.3.0

#  flutter_sound_lite: ^8.4.1
#  flutter_ffmpeg: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/langs/
    - assets/images/
    - assets/lottiefiles/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  #
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 700

    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
